services:
  - type: web
    name: classsync
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/teachers
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false